excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://tayl0rt.github.io
title: Taylor Thompson
tagline: Web Nerd
description: Hi! I write software. Welcome to my random happenings.
twitter: "@tayl0rt"
paginate: 5
